export const works = [
  {
    id: 1,
    title: "Сложное окрашивание",
    category: "hair",
    categoryName: "Парикмахерские услуги",
    master: "Мария Петрова",
    date: "Март 2024",
    description: "Техника air touch с использованием премиальных красителей",
    beforeAfter: true,
    likes: 156,
    views: 1240,
    image: "/works/hair-1.jpg",
  },
  {
    id: 2,
    title: "Свадебный макияж",
    category: "makeup",
    categoryName: "Макияж",
    master: "Анастасия Волкова",
    date: "Февраль 2024",
    description: "Нежный образ для особого дня, стойкий макияж",
    beforeAfter: false,
    likes: 234,
    views: 1890,
    image: "/works/makeup-1.jpg",
  },
  {
    id: 3,
    title: "Дизайн ногтей",
    category: "nails",
    categoryName: "Маникюр и педикюр",
    master: "Светлана Михайлова",
    date: "Март 2024",
    description: "Художественная роспись с использованием страз и втирки",
    beforeAfter: true,
    likes: 98,
    views: 756,
    image: "/works/nails-1.jpg",
  },
  {
    id: 4,
    title: "Ламинирование бровей",
    category: "brows",
    categoryName: "Брови и ресницы",
    master: "Алина Козлова",
    date: "Февраль 2024",
    description: "Идеальная форма и укладка на 4-6 недель",
    beforeAfter: true,
    likes: 187,
    views: 1430,
    image: "/works/brows-1.jpg",
  },
  {
    id: 5,
    title: "Женская стрижка",
    category: "hair",
    categoryName: "Парикмахерские услуги",
    master: "Анна Петрова",
    date: "Март 2024",
    description: "Модная каскадная стрижка с текстурой",
    beforeAfter: false,
    likes: 123,
    views: 980,
    image: "/works/hair-2.jpg",
  },
  {
    id: 6,
    title: "Вечерний макияж",
    category: "makeup",
    categoryName: "Макияж",
    master: "Анастасия Волкова",
    date: "Январь 2024",
    description: "Яркий образ с акцентом на глаза",
    beforeAfter: false,
    likes: 245,
    views: 2100,
    image: "/works/makeup-2.jpg",
  },
  {
    id: 7,
    title: "SPA-уход за лицом",
    category: "cosmetology",
    categoryName: "Косметология",
    master: "Елена Соколова",
    date: "Февраль 2024",
    description: "Комплексная программа восстановления кожи",
    beforeAfter: true,
    likes: 89,
    views: 670,
    image: "/works/cosmetology-1.jpg",
  },
  {
    id: 8,
    title: "Мужская стрижка",
    category: "hair",
    categoryName: "Парикмахерские услуги",
    master: "Дмитрий Волков",
    date: "Март 2024",
    description: "Модельная стрижка с оформлением бороды",
    beforeAfter: true,
    likes: 145,
    views: 1120,
    image: "/works/hair-3.jpg",
  },
  {
    id: 9,
    title: "Педикюр",
    category: "nails",
    categoryName: "Маникюр и педикюр",
    master: "Татьяна Смирнова",
    date: "Февраль 2024",
    description: "Аппаратный педикюр с покрытием гель-лаком",
    beforeAfter: false,
    likes: 76,
    views: 540,
    image: "/works/nails-2.jpg",
  },
  {
    id: 10,
    title: "Коррекция бровей",
    category: "brows",
    categoryName: "Брови и ресницы",
    master: "Алина Козлова",
    date: "Март 2024",
    description: "Коррекция формы и окрашивание хной",
    beforeAfter: true,
    likes: 167,
    views: 1280,
    image: "/works/brows-2.jpg",
  },
  {
    id: 11,
    title: "Спа-программа",
    category: "spa",
    categoryName: "Спа-процедуры",
    master: "Ольга Ветрова",
    date: "Январь 2024",
    description: "Полное расслабление и восстановление",
    beforeAfter: false,
    likes: 112,
    views: 890,
    image: "/works/spa-1.jpg",
  },
  {
    id: 12,
    title: "Окрашивание омбре",
    category: "hair",
    categoryName: "Парикмахерские услуги",
    master: "Мария Петрова",
    date: "Февраль 2024",
    description: "Плавное вытяжение цвета для натурального эффекта",
    beforeAfter: true,
    likes: 203,
    views: 1670,
    image: "/works/hair-4.jpg",
  },
];
