export const makeupArtistsList = [
  {
    name: "Анастасия Волкова",
    position: "Визажист-стилист",
    exp: "8 лет",
    rating: 5.0,
    specialization: "Свадебный, вечерний, fashion макияж",
    education: "Школа визажа Makeup Atelier",
    image: "/masters/anastasia.jpg",
    works: 1500,
  },
  {
    name: "Дарья Соколова",
    position: "Визажист-универсал",
    exp: "6 лет",
    rating: 4.9,
    specialization: "Дневной, вечерний, возрастной макияж",
    education: "Международная школа визажа",
    image: "/masters/daria.jpg",
    works: 1200,
  },
  {
    name: "Екатерина Морозова",
    position: "Топ-визажист",
    exp: "10 лет",
    rating: 5.0,
    specialization: "Свадебный, fashion, портретный макияж",
    education: "London School of Makeup",
    image: "/masters/ekaterina.jpg",
    works: 2000,
  },
  {
    name: "Ксения Петрова",
    position: "Визажист",
    exp: "5 лет",
    rating: 4.8,
    specialization: "Дневной, вечерний, экспресс-макияж",
    education: "Школа стиля и визажа",
    image: "/masters/ksenia.jpg",
    works: 800,
  },
];
